theme: jekyll-theme-cayman
title: 段红妃的个人主页
description: Personal Homepage


# social
author: lorepirri
image: /portrait.png
twitter:
  username: lorepirri

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
